### ISSUE TITLE
Unnecessary selector bloat with grid modifiers

### ISSUE THREAD

**Issue by fspoettel** [csswizardry/csswizardry-grids#67]
Using grid modifiers causes unnecessary selector bloat that quickly runs out of control if used frequently. [Gzip should solve this but I still think it is bad authoring to generate a lot of completely useless selectors for declaring margins and paddings on the grid when this can be avoided] This is caused by nesting grid__item directly under grid--modifier. One can use something like uncss to combat this, but there is quite an easy solution that needs the author to write one more line of SCSS. The modifiers should be written like this:

``` css
%grid--center{
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align:center;

}

%grid--center__item{
    text-align:left;
}
```

and declared like this:

``` css
header {
    @extend %grid;
    @extend %grid--full;
}

header > article {
    @extend %grid__item;
    @extend %grid--full__item;
}
```
